Controllers/HomeworkController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationForDidacticPurpose.BL.Interfaces;
using WebApplicationForDidacticPurpose.DAL.Models;
using WebApplicationForDidacticPurpose.MODELS.ViewModels;
using WebApplicationForDidacticPurpose.MODELS.ViewModels.Homework;
using WebApplicationForDidacticPurpose.Utility;

namespace WebApplicationForDidacticPurpose.Controllers
{
    public class HomeworkController : Controller
    {
        private readonly IHomeworkService _homeworkService;
        private readonly IMapper _mapper;
        private readonly INotyfService _notifyService;
        private readonly UserManager<User> _userManager;

        public HomeworkController(IHomeworkService homeworkService, IMapper mapper,
            INotyfService notyfService, UserManager<User> userManager)
        {
            _homeworkService = homeworkService;
            _mapper = mapper;
            _notifyService = notyfService;
            _userManager = userManager;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(string searchString, int? pageNumber)
        {
            int pageSize = 5;
            ViewData["CurrentFilter"] = searchString;
            var homeworks = _homeworkService.GetAllHomeworks();

            if (!string.IsNullOrEmpty(searchString))
            {
                homeworks = homeworks.Where(t => t.Name.Contains(searchString));
            }
            ///homeworks = homeworks.OrderBy(t => t.Name);
            /// var mapper = _mapper.Map<HomeworkViewModel>(homeworks);

            return View(await PaginatedList<HomeworkEntity>.CreateAsync(homeworks, pageNumber ?? 1, pageSize));
        }


        [Authorize(Roles = "Trainer")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Trainer")]
        [HttpPost]
        public async Task<IActionResult> Create(HomeworkViewModel homeworkView)
        {
            var homework = _mapper.Map<HomeworkEntity>(homeworkView);
            homework.Index = _homeworkService.AssignHomeworkIndex();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            homework.Trainer = user;
            if (_homeworkService.GetHomeworkByName(homework.Name) != null)
            {
                _notifyService.Warning("Homework name already exists");
                return View();
            }

            var result = _homeworkService.AddHomework(homework);

            if (result)
            {
                ModelState.Clear();

                _notifyService.Success("Homework created!");
                _homeworkService.RegroupIndexForAllHomeworks();
                return RedirectToAction("Index");
            }
            return View("~/Views/Shared/AnyError.cshtml",
                    new ErrorMessageViewModel("The homework could not be created, please try again.", ErrorType.RequestProcessingError));
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int homeworkId)
        {
            var homework = _homeworkService.GetHomeworkById(homeworkId);

            /// var user = await _userManager.GetUserAsync(HttpContext.User);
            if (homework != null)
            {
                ///_notifyService.Success(homework.Trainer.Email);
                return View(homework);
            }

            return View("~/Views/Shared/AnyError.cshtml",
                    new ErrorMessageViewModel("We cannot find the homework you are looking for.", ErrorType.NotFoundError));
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public IActionResult DeleteGet(int homeworkId)
        {
            var homework = _homeworkService.GetHomeworkById(homeworkId);

            if (homework == null)
            {
                return View("~/Views/Shared/AnyError.cshtml",
                   new ErrorMessageViewModel("We cannot find the homework you are looking for.", ErrorType.NotFoundError));
            }

            return View("Delete", homework);
        }
        [Authorize(Roles = "Trainer")]
        [HttpPost]
        public IActionResult Delete(int homeworkId)
        {
            var homework = _homeworkService.GetHomeworkById(homeworkId);

            if (homework == null)
            {
                return View("~/Views/Shared/AnyError.cshtml",
                   new ErrorMessageViewModel("We cannot find the homework you are looking for.", ErrorType.NotFoundError));
            }

            var result = _homeworkService.DeleteHomeworkById(homeworkId);

            if (result)
            {
                _homeworkService.RegroupIndexForAllHomeworks();
                _notifyService.Success("Homework deleted");
                return RedirectToAction("Index");
            }

            return View("~/Views/Shared/AnyError.cshtml",
                    new ErrorMessageViewModel("The homework could not be deleted, please try again.", ErrorType.RequestProcessingError));
        }

        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public IActionResult Edit(int homeworkId)
        {
            var homework = _homeworkService.GetHomeworkById(homeworkId);

            if (homework == null)
            {
                return View("~/Views/Shared/AnyError.cshtml",
                    new ErrorMessageViewModel("We cannot find the homework you are looking for.", ErrorType.NotFoundError));
            }

            return View(homework);
        }

        [HttpPost]
        [Authorize(Roles = "Trainer")]
        public IActionResult Edit(HomeworkViewModel homework)
        {
            var homeworkMapper = _mapper.Map<HomeworkEntity>(homework);
            homeworkMapper.Name = _homeworkService.GetHomeworkById(homework.HomeworkId).Name;
            var result = _homeworkService.UpdateHomework(homeworkMapper);

            if (result)
            {
                _notifyService.Success("Homework was edited!");
                return RedirectToAction("Index");
            }
            else
            {
                return View("~/Views/Shared/AnyError.cshtml",
                    new ErrorMessageViewModel("The homework could not be updated, please try again.", ErrorType.RequestProcessingError));
            }
        }
    }
}

Views/Shared/AnyError.cshtml
@model WebApplicationForDidacticPurpose.MODELS.ViewModels.ErrorMessageViewModel

@{ ViewData["Title"] = "Home Page"; }

<section class="container-fluid d-flex align-items-center justify-content-center mt-5">
    <div class="row d-flex flex-md-row flex-column align-items-center justify-content-center">

        <div class="col-6 order-first p-3">
            <div class="text-center">
                @if (@Model.Type == WebApplicationForDidacticPurpose.MODELS.ViewModels.ErrorType.RequestProcessingError)
                {
    <img src="~/images/error-processing-request-image.svg" class="rounded img-fluid mx-auto d-block" height="500" width="500" alt="..." /> }
                else if (@Model.Type == WebApplicationForDidacticPurpose.MODELS.ViewModels.ErrorType.NotFoundError)
                {
    <img src="~/images/error-not-found-image.svg" class="rounded img-fluid mx-auto d-block" height="500" width="500" alt="..." />}
            </div>
        </div>

        <div class="col-6 order-last p-3">
            <h1>Error.</h1>
            <h2>@Model.Message</h2>
        </div>
    </div>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasySchool</title>
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/school.ico" />
</head>
<body class="d-flex flex-column min-vh-100">
    @if (User.Identity.IsAuthenticated)
    {
<header class="sticky-top">
    <nav class="navbar navbar-expand-md navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Homework" asp-action="Index">
                <img src="~/images/Logo.svg" alt="" width="55" height="40" class="d-inline-block align-text-top">
                <p class="m-0">EasySchool</p>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link text-dark">Hi, @User.Identity.Name!</a>
                    </li>
                    @if (User.IsInRole("User"))
                    {
    <li class="nav-item">
        <a class="nav-link text-dark @Html.ActiveClass("Attendee", "MyAccount")" asp-area="" asp-controller="Attendee" asp-action="MyAccount">My Account</a>
    </li>
}

                    @if (User.IsInRole("Trainer"))
                    {
    <li class="nav-item">
        <a class="nav-link text-dark @Html.ActiveClass("Attendee", "Index")" asp-area="" asp-controller="Attendee" asp-action="Index">Attendees</a>
    </li>
}
                    <li class="nav-item">
                        <a class="nav-link text-dark @Html.ActiveClass("Homework", "Index")" asp-area="" asp-controller="Homework" asp-action="Index">Homeworks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>}

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*
                @if (User.Identity.IsAuthenticated)
                {
            <footer class="mt-auto" style="background-color: #F0F3F3;">
                <div class="container p-4 pb-0 mt-5">
                    <div class="row">
                        <div class="col-lg-6 col-md-12 mb-4">
                            <h5 class="mb-3 text-dark">ENDAVA</h5>
                            <span>
                                We don't simply deliver projects. We work closely with you to understand your
                                challenges, the demands the market is making on your organisation and design,
                                build, operate and support the secure, scalable platforms that position you
                                as a disruptor within the marketplace.
                            </span>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4">
                            <h5 class="mb-3 text-dark">IS ABOUT</h5>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-1">
                                    Thoughtful
                                </li>
                                <li class="mb-1">
                                    Open
                                </li>
                                <li class="mb-1">
                                    Adaptable
                                </li>
                                <li>
                                    Smart
                                </li>
                                <li>
                                    Trusted
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-1">
                            <h5 class="mb-1 text-dark text-center">CONTACT</h5>
                            <ul class="list-unstyled mb-0 text-center">
                                <li class="mb-1">
                                    <i class="bi bi-geo-alt"></i> 51 Al. Vaida Voevod St. 400436,
                                    Cluj, Romania
                                </li>
                                <li class="mb-1">
                                    <i class="bi bi-telephone"></i> +40 372 363 282
                                </li>
                                <li class="mb-1 text-dark">
                                    <i class="bi bi-envelope"></i>
                                    <a href="mailto:info.cluj@endava.com">info.cluj@endava.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                    Copyright Endava 2021.
                </div>
        </footer>}
    *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await Component.InvokeAsync("Notyf")

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Pagination.cshtml
@{ var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                var actionName = ViewContext.RouteData.Values["action"].ToString(); }


@if (Model.TotalPages > 0)
{
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item @prevDisabled">
            <a asp-action="@actionName"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex - 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                Previous
            </a>
        </li>
        @if (Model.PageIndex != 1)
        {
<li class="page-item">
    <a asp-action="@actionName"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="1"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="page-link">
        1
    </a>
</li>}

        <li class="page-item">
            <a asp-action="@actionName"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                <u>@(Model.PageIndex)</u>
            </a>
        </li>


        @if (Model.PageIndex != Model.TotalPages)
        {
<li class="page-item">
    <a asp-action="@actionName"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.TotalPages)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="page-link">
        @(Model.TotalPages)
    </a>
</li>}


        <li class="page-item @nextDisabled">
            <a asp-action="@actionName"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex + 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                Next
            </a>
        </li>
    </ul>
</nav> }
            else
            {
<p class="text-center">No results found!</p>}